### ISSUE TITLE
Template: Chain Addition Checklist

### ISSUE THREAD

**Issue by mvpratt** [shapeshift/unchained#55]
How to add a new chain.  Note - this template is only a guide.  Each chain is different so make changes to the plan as neccesary

**Daemon**
- [ ] Spike: Select a blockchain daemon.
- [ ] Update the Pulumi infra code, add init.sh and readiness.sh scripts
- [ ] Deploy

**Indexer**
The Indexer maintains an index of transaction history by address.  Most nodes don't do this so a separate database is needed.
- [ ] Spike: Select an indexer. For UTXO and EVM chains, use Blockbook.  For Cosmos chains (Cosmos, Binance, Thorchain) use the node
- [ ] Update the Pulumi infra code
- [ ] Deploy

**API**
The API is an adapter layer to the Indexer that provides a consistent set of endpoints for the ShapeShift client.  Implement these endpoints using Bitcoin & Ethereum as a reference
- [ ] `/account{pubkey}`
- [ ] `/account/{pubkey}/txs`
- [ ] `/account/{pubkey}/utxos`
- [ ] `/send`

**Ingester**
The Ingester filters new transactions and sends only the relevant ones to each client
- [ ] Get new blocks (ws)
- [ ] Get transactions from mempool (ws)
- [ ] Get transactions from confirmed blocks
- [ ] Filter for transactions for addresses in the registry
- [ ] Handle reorgs
- [ ] Delta sync on register
- [ ] Delta sync on new transaction
- [ ] Client web sockets

**Tests - Ingester**
- [ ] newBlock worker: Block Reorg
- [ ] Tx worker: Delta sync
- [ ] Tx worker: parseTx
(TODO: add more tests)
